In [ ]:
#using pure Python to calculate W*x+B
#there is no any import library/module
#  4 inputs into 3 neuron of outputs
inputs=[1,2,3,4]
weights=[[0.8,-0.76,0.99,-0.514],
         [-0.3,-0.45,0.765,0.81],
         [0.23,0.38,-0.41,-0.72]]
biases=[1.02,2,1.5]
output_py=[inputs[0]*weights[0][0]+inputs[1]*weights[0][1]+inputs[2]*weights[0][2]+inputs[3]*weights[0][3]+biases[0],
           inputs[0]*weights[1][0]+inputs[1]*weights[1][1]+inputs[2]*weights[1][2]+inputs[3]*weights[1][3]+biases[1],
           inputs[0]*weights[2][0]+inputs[1]*weights[2][1]+inputs[2]*weights[2][2]+inputs[3]*weights[2][3]+biases[2],
]
print(output_py)

#if there are many inputs and weights, then coding as follow:
layer_outputs=[] #output current layer
for neuron_weights, neuron_bias in zip(weights,biases):
  neuron_output=0 # output of a given neuron
  for n_input,weight in zip(inputs,neuron_weights):
    neuron_output += n_input * weight
  neuron_output +=neuron_bias
  layer_outputs.append(neuron_output)
print(layer_outputs)


[1.214, 6.335, -1.62]
[1.214, 6.335, -1.62]


In [ ]:
#using Numpy to calculate W*x+B
import numpy as np
#tensorflow calculats w*x+b via numpy and then convert the result into the tensor
import tensorflow as tf
inputs=np.array([1,2,3,4])
weights=np.array([[0.8,-0.76,0.99,-0.514],
         [-0.3,-0.45,0.765,0.81],
         [0.23,0.38,-0.41,-0.72]])
biases=np.array([1.02,2,1.5])

output_np=np.dot(weights,inputs)+biases
output_tf=tf.convert_to_tensor(output_np)
print(output_np)
print(output_tf)

[ 1.214  6.335 -1.62 ]
tf.Tensor([ 1.214  6.335 -1.62 ], shape=(3,), dtype=float64)


In [ ]:
#using Pytorch to calculate W*x+B
import torch

inputs=torch.tensor([1.,2.,3.,4.],dtype=torch.float32)
weights=torch.tensor([[0.8,-0.76,0.99,-0.514],
         [-0.3,-0.45,0.765,0.81],
         [0.23,0.38,-0.41,-0.72]],dtype=torch.float32)
biases=torch.tensor([1.02,2,1.5],dtype=torch.float32)
print(weights.shape)
print(inputs.shape)
print(biases.shape)
inputs=inputs.view(inputs.shape[0],1)
biases=biases.view(biases.shape[0],1)
print(inputs.shape)
print(biases.shape)

output_torch=torch.matmul(weights,inputs)+biases
print(output_torch)
print(output_torch.shape)
print("after reshape of output_torch")
output_torch=output_torch.view(output_torch.shape[0])
print(output_torch)
print(output_torch.shape)

torch.Size([3, 4])
torch.Size([4])
torch.Size([3])
torch.Size([4, 1])
torch.Size([3, 1])
tensor([[ 1.2140],
        [ 6.3350],
        [-1.6200]])
torch.Size([3, 1])
after reshape of output_torch
tensor([ 1.2140,  6.3350, -1.6200])
torch.Size([3])


In [ ]:
a = torch.rand(2, 3)
b = torch.rand(3, 2)

#print(a * b)
print(torch.matmul(a,b))

tensor([[0.5915, 0.3654],
        [1.2229, 0.6001]])


In [ ]:
#using tensorflow to calculate W*x+B
import tensorflow as tf
inputs=tf.Variable([[1,2,3,4]],dtype=tf.float32)
weights=tf.Variable([[0.8,-0.76,0.99,-0.514],
         [-0.3,-0.45,0.765,0.81],
         [0.23,0.38,-0.41,-0.72]],dtype=tf.float32)
biases=tf.Variable([[1.02,2,1.5]],dtype=tf.float32)
print(weights.shape)
print(inputs.shape)
print(biases.shape)
#need to transpose matrix
print(tf.transpose(inputs).shape)
print(tf.transpose(biases).shape)
output_tf=tf.matmul(weights,tf.transpose(inputs))+tf.transpose(biases)
print(output_tf)

#flatten for vector
output_tf_flatten=tf.reshape(output_tf,[-1])
print(output_tf_flatten.shape)
print(output_tf_flatten)

print("\nndim size compared")
print(output_tf.ndim)
print(output_tf_flatten.ndim)

(3, 4)
(1, 4)
(1, 3)
(4, 1)
(3, 1)
tf.Tensor(
[[ 1.214    ]
 [ 6.335    ]
 [-1.6200001]], shape=(3, 1), dtype=float32)
(3,)
tf.Tensor([ 1.214      6.335     -1.6200001], shape=(3,), dtype=float32)

ndim size compared
2
1


In [ ]:
a = tf.constant([1, 2, 3, 4, 5, 6], shape=[2, 3])
b = tf.constant([7, 8, 9, 10, 11, 12], shape=[3, 2])
c = tf.matmul(a, b)
print(c)

tf.Tensor(
[[ 58  64]
 [139 154]], shape=(2, 2), dtype=int32)


In [ ]:
w = tf.Variable([[1.], [2.]])
x = tf.Variable([[3., 4.]])
#x = tf.constant([[3., 4.]])
print(w.shape)
print(x.shape)
tf.matmul(w, x)

(2, 1)
(1, 2)


<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[3., 4.],
       [6., 8.]], dtype=float32)>

In [14]:
# Batches, Layers, and Objects
#Hidden Layer Activation Functions
import numpy as np
np.random.seed(0)
#inputs [3,4], batchsize=3
#define hidden layer as an object
# The object has 3 features of weights, biases and output
# hidden layer size: the 1st hidden layer has 5 neurons and the 2nd hidden layer has 2 output neurons
X=[[1.,2.,3.,2.5],
   [2.0,5.0,-1,-0.8],
   [0.7,1.7,2.9,-3.2]]

class Layer_dense:
  def __init__(self, n_inputs,n_neurons):
    self.weights=0.10*np.random.randn(n_inputs,n_neurons)
    self.biases=np.zeros((1,n_neurons))
  def forward(self,inputs):
    self.output=np.dot(inputs,self.weights)+self.biases
  
class Activation_Relu:
  def forward(self,inputs):
    self.output=np.maximum(0,inputs)

class Activation_Softmax:
  def forward(self,inputs):
    exp_values=np.exp(inputs-np.max(inputs,axis=1,keepdims=True))
    probabilities=exp_values/np.sum(exp_values,axis=1,keepdims=True)
    self.output=probabilities

#you may design the number of hidden layer neurons what you want 
print("\nThe 1st hidder layer outputs\n")
layer1=Layer_dense(4,6)
#activation1=Activation_Relu()
activation1=Activation_Softmax()
#layer1.forward(inputs)
layer1.forward(X)
print(layer1.output)
activation1.forward(layer1.output)
print(activation1.output)
#print(np.sum(activation1.output))
print("\nThe 2nd hidder layer outputs\n")

layer2=Layer_dense(6,3)
#activation2=Activation_Relu()
activation2=Activation_Softmax()
layer2.forward(activation1.output)
print(layer2.output)
activation2.forward(layer2.output)
print(activation2.output)
#print(np.sum(activation2.output))




The 1st hidder layer outputs

[[ 0.67300116 -0.16727715 -0.42785846  0.56971597  0.87989728 -0.05396182]
 [ 0.72670549  0.060513    0.30399103  0.56782097  0.22697058  0.61157021]
 [ 0.40551797  0.31087667  0.99664153  0.11427187  0.31187981  0.35681395]]
[[0.22834831 0.09855294 0.07594524 0.20594043 0.28083527 0.11037781]
 [0.22124098 0.11364278 0.14497163 0.18873955 0.13422502 0.19718004]
 [0.15807471 0.14380044 0.28548553 0.11813425 0.14394476 0.15056031]]

The 2nd hidder layer outputs

[[ 0.04158301 -0.00020379 -0.01454795]
 [ 0.02350267 -0.02037822 -0.0254077 ]
 [ 0.02736881  0.00725813 -0.02860041]]
[[0.34429458 0.33020406 0.32550137]
 [0.34372123 0.32896457 0.3273142 ]
 [0.3418034  0.33499816 0.32319844]]


In [10]:
# Batches, Layers, and Objects
import numpy as np
np.random.seed(0)
#inputs [3,4], batchsize=3
#define hidden layer as an object
# The object has 3 features of weights, biases and output
# hidden layer size: the 1st hidden layer has 6 neurons and the 2nd hidden layer has 2 output neurons
X=[[1.,2.,3.,2.5],
   [2.0,5.0,-1,-0.8],
   [0.7,1.7,2.9,-3.2]]

class Layer_dense:
  def __init__(self, n_inputs,n_neurons):
    self.weights=0.10*np.random.randn(n_inputs,n_neurons)
    self.biases=np.zeros((1,n_neurons))
  def forward(self,inputs):
    self.output=np.dot(inputs,self.weights)+self.biases

#you may design the number of hidden layer neurons what you want 
layer1=Layer_dense(4,6)
layer2=Layer_dense(6,2)

#layer1.forward(inputs)
layer1.forward(X)
print(layer1.output)
layer2.forward(layer1.output)
print(layer2.output)


[[ 0.67300116 -0.16727715 -0.42785846  0.56971597  0.87989728 -0.05396182]
 [ 0.72670549  0.060513    0.30399103  0.56782097  0.22697058  0.61157021]
 [ 0.40551797  0.31087667  0.99664153  0.11427187  0.31187981  0.35681395]]
[[ 0.01899703 -0.31120449]
 [ 0.17918717 -0.07607862]
 [ 0.20789667  0.02976919]]


In [ ]:
bias=np.zeros((1,6))
bias_tf=tf.convert_to_tensor(bias)
bias_tf=tf.transpose(bias_tf)
print(bias_tf.shape)

(6, 1)


In [23]:
# Batches, Layers, and Objects
import tensorflow as tf
import numpy as np
np.random.seed(0)
#inputs [3,4], batchsize=3
#define hidden layer as an object
# The object has 3 features of weights, biases and output
# hidden layer size: the 1st hidden layer has 6 neurons and the 2nd hidden layer has 2 output neurons
X=[[1.,2.,3.,2.5],
   [2.0,5.0,-1,-0.8],
   [0.7,1.7,2.9,3.2]]

class Layer_dense:
  def __init__(self, n_inputs,n_neurons):
    self.weights=0.10*np.random.randn(n_inputs,n_neurons)
    self.biases=np.zeros((1,n_neurons))
  def forward(self,inputs):
    self.output=np.dot(inputs,self.weights)+self.biases
    
#you may design the number of hidden layer neurons what you want 
layer1=Layer_dense(4,6)
layer2=Layer_dense(6,2)
outputs=[[]]
for inputs in X: 
  layer1.forward(inputs)
  print(layer1.output)
  layer2.forward(layer1.output)
  print(layer2.output)
  outputs.append(layer2.output)
print(outputs)
print(outputs[0])
print(outputs[1])
print(outputs[2])
print(outputs[3])





[[ 0.67300116 -0.16727715 -0.42785846  0.56971597  0.87989728 -0.05396182]]
[[ 0.01899703 -0.31120449]]
[[0.72670549 0.060513   0.30399103 0.56782097 0.22697058 0.61157021]]
[[ 0.17918717 -0.07607862]]
[[ 0.6058813  -0.2357446  -0.63727195  0.53258777  0.86511898 -0.11817166]]
[[-0.02567865 -0.33041224]]
[[], array([[ 0.01899703, -0.31120449]]), array([[ 0.17918717, -0.07607862]]), array([[-0.02567865, -0.33041224]])]
[]
[[ 0.01899703 -0.31120449]]
[[ 0.17918717 -0.07607862]]
[[-0.02567865 -0.33041224]]


In [7]:
# Batches, Layers, and Objects
import tensorflow as tf
import numpy as np
np.random.seed(0)
#inputs [3,4], batchsize=3
#define hidden layer as an object
# The object has 3 features of weights, biases and output
# hidden layer size: the 1st hidden layer has 6 neurons and the 2nd hidden layer has 2 output neurons
X=[[1.,2.,3.,2.5],
   [2.0,5.0,-1,-0.8],
   [0.7,1.7,2.9,3.2]]

class Layer_dense:
  def __init__(self, n_inputs,n_neurons):
    self.weights=0.10*np.random.randn(n_inputs,n_neurons)
    self.biases=np.zeros((1,n_neurons))
  def forward(self,inputs):
    self.output=np.dot(inputs,self.weights)+self.biases
    
#you may design the number of hidden layer neurons what you want 
layer1=Layer_dense(4,6)
layer2=Layer_dense(6,2)
layer1.forward(X)
print(layer1.output)
layer2.forward(layer1.output)
print(layer2.output)
outputs.append(layer2.output)


[[ 0.67300116 -0.16727715 -0.42785846  0.56971597  0.87989728 -0.05396182]
 [ 0.72670549  0.060513    0.30399103  0.56782097  0.22697058  0.61157021]
 [ 0.6058813  -0.2357446  -0.63727195  0.53258777  0.86511898 -0.11817166]]
[[ 0.01899703 -0.31120449]
 [ 0.17918717 -0.07607862]
 [-0.02567865 -0.33041224]]


In [6]:
#Calculating Loss with Categorical Cross-Entropy
import math
softmax_output=[0.7,0.2,0.1]
target_label=[1,0,0] # one hot coding, class=3, label=0
loss=-(math.log(softmax_output[0])*target_label[0]+
       math.log(softmax_output[1])*target_label[1]+
       math.log(softmax_output[2])*target_label[2])
print(loss)

loss=-math.log(0.7)
print(loss)
#when high probability, corresponding to low loss. 
loss=-math.log(0.9)
print(loss)
      
loss=-math.log(0.1)
print(loss)

0.35667494393873245
0.35667494393873245
0.10536051565782628
2.3025850929940455


In [ ]:
#Calculating Loss with Categorical Cross-Entropy

#Implementing Loss



In [16]:
import numpy as np
a=[[0.7,0.2,0.1],[0.1,0.5,0.4],[0.02,0.9,0.08]]
b=[[1.,0.,0.],[0.,1.,0.],[0.,1.,0.]]
c=np.matmul(a,b)
d=np.dot(a,b)
print(c)
print(d)

sum=np.sum(c,axis=1)
print(sum)

sum=np.sum(c,axis=0)
print(sum)


[[0.7  0.3  0.  ]
 [0.1  0.9  0.  ]
 [0.02 0.98 0.  ]]
[[0.7  0.3  0.  ]
 [0.1  0.9  0.  ]
 [0.02 0.98 0.  ]]
[1. 1. 1.]
[0.82 2.18 0.  ]


In [20]:
#metric for accuracy calculation
import numpy as np
softmax_output=np.array([[0.7,0.2,0.1],
                         [0.1,0.5,0.4],
                         [0.02,0.9,0.08]])
class_targets=[0,1,1]
prediction=np.argmax(softmax_output,axis=1)
print(prediction)
accuracy=np.mean(prediction==class_targets)
print("acc:",accuracy)

[0 1 1]
acc: 1.0


In [19]:
import numpy as np
softmax_output=np.array([[0.7,0.2,0.1],
                         [0.5,0.1,0.4],
                         [0.02,0.9,0.08]])
class_targets=[0,1,1]
prediction=np.argmax(softmax_output,axis=1)
print(prediction)
accuracy=np.mean(prediction==class_targets)
print("acc:",accuracy)

[0 0 1]
acc: 0.6666666666666666
