In [83]:
#using pure Python to calculate W*x+B
#there is no any import library/module
#  4 inputs into 3 neuron of outputs
inputs=[1,2,3,4]
weights=[[0.8,-0.76,0.99,-0.514],
         [-0.3,-0.45,0.765,0.81],
         [0.23,0.38,-0.41,-0.72]]
biases=[1.02,2,1.5]
output_py=[inputs[0]*weights[0][0]+inputs[1]*weights[0][1]+inputs[2]*weights[0][2]+inputs[3]*weights[0][3]+biases[0],
           inputs[0]*weights[1][0]+inputs[1]*weights[1][1]+inputs[2]*weights[1][2]+inputs[3]*weights[1][3]+biases[1],
           inputs[0]*weights[2][0]+inputs[1]*weights[2][1]+inputs[2]*weights[2][2]+inputs[3]*weights[2][3]+biases[2],
]
print(output_py)

#if there are many inputs and weights, then coding as follow:
layer_outputs=[] #output current layer
for neuron_weights, neuron_bias in zip(weights,biases):
  neuron_output=0 # output of a given neuron
  for n_input,weight in zip(inputs,neuron_weights):
    neuron_output += n_input * weight
  neuron_output +=neuron_bias
  layer_outputs.append(neuron_output)
print(layer_outputs)


[1.214, 6.335, -1.62]
[1.214, 6.335, -1.62]


In [58]:
#using Numpy to calculate W*x+B
import numpy as np
#tensorflow calculats w*x+b via numpy and then convert the result into the tensor
import tensorflow as tf
inputs=np.array([1,2,3,4])
weights=np.array([[0.8,-0.76,0.99,-0.514],
         [-0.3,-0.45,0.765,0.81],
         [0.23,0.38,-0.41,-0.72]])
biases=np.array([1.02,2,1.5])

output_np=np.dot(weights,inputs)+biases
output_tf=tf.convert_to_tensor(output_np)
print(output_np)
print(output_tf)

[ 1.214  6.335 -1.62 ]
tf.Tensor([ 1.214  6.335 -1.62 ], shape=(3,), dtype=float64)


In [80]:
#using Pytorch to calculate W*x+B
import torch

inputs=torch.tensor([1.,2.,3.,4.],dtype=torch.float32)
weights=torch.tensor([[0.8,-0.76,0.99,-0.514],
         [-0.3,-0.45,0.765,0.81],
         [0.23,0.38,-0.41,-0.72]],dtype=torch.float32)
biases=torch.tensor([1.02,2,1.5],dtype=torch.float32)
print(weights.shape)
print(inputs.shape)
print(biases.shape)
inputs=inputs.view(inputs.shape[0],1)
biases=biases.view(biases.shape[0],1)
print(inputs.shape)
print(biases.shape)

output_torch=torch.matmul(weights,inputs)+biases
print(output_torch)
print(output_torch.shape)
print("after reshape of output_torch")
output_torch=output_torch.view(output_torch.shape[0])
print(output_torch)
print(output_torch.shape)

torch.Size([3, 4])
torch.Size([4])
torch.Size([3])
torch.Size([4, 1])
torch.Size([3, 1])
tensor([[ 1.2140],
        [ 6.3350],
        [-1.6200]])
torch.Size([3, 1])
after reshape of output_torch
tensor([ 1.2140,  6.3350, -1.6200])
torch.Size([3])


In [41]:
a = torch.rand(2, 3)
b = torch.rand(3, 2)

#print(a * b)
print(torch.matmul(a,b))

tensor([[0.5915, 0.3654],
        [1.2229, 0.6001]])


In [3]:
#using tensorflow to calculate W*x+B
import tensorflow as tf
inputs=tf.Variable([[1,2,3,4]],dtype=tf.float32)
weights=tf.Variable([[0.8,-0.76,0.99,-0.514],
         [-0.3,-0.45,0.765,0.81],
         [0.23,0.38,-0.41,-0.72]],dtype=tf.float32)
biases=tf.Variable([[1.02,2,1.5]],dtype=tf.float32)
print(weights.shape)
print(inputs.shape)
print(biases.shape)
#need to transpose matrix
print(tf.transpose(inputs).shape)
print(tf.transpose(biases).shape)
output_tf=tf.matmul(weights,tf.transpose(inputs))+tf.transpose(biases)
print(output_tf)

#flatten for vector
output_tf_flatten=tf.reshape(output_tf,[-1])
print(output_tf_flatten.shape)
print(output_tf_flatten)

print("\nndim size compared")
print(output_tf.ndim)
print(output_tf_flatten.ndim)

(3, 4)
(1, 4)
(1, 3)
(4, 1)
(3, 1)
tf.Tensor(
[[ 1.214    ]
 [ 6.335    ]
 [-1.6200001]], shape=(3, 1), dtype=float32)
(3,)
tf.Tensor([ 1.214      6.335     -1.6200001], shape=(3,), dtype=float32)

ndim size compared
2
1


In [70]:
a = tf.constant([1, 2, 3, 4, 5, 6], shape=[2, 3])
b = tf.constant([7, 8, 9, 10, 11, 12], shape=[3, 2])
c = tf.matmul(a, b)
print(c)

tf.Tensor(
[[ 58  64]
 [139 154]], shape=(2, 2), dtype=int32)


In [82]:
w = tf.Variable([[1.], [2.]])
x = tf.Variable([[3., 4.]])
#x = tf.constant([[3., 4.]])
print(w.shape)
print(x.shape)
tf.matmul(w, x)

(2, 1)
(1, 2)


<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[3., 4.],
       [6., 8.]], dtype=float32)>

In [18]:
# Batches, Layers, and Objects
##Hidden Layer Activation Functions
import numpy as np

np.random.seed(0)
#inputs [3,4], batchsize=3
#define hidden layer as an object
# The object has 3 features of weights, biases and output
# hidden layer size: the 1st hidden layer has 5 neurons and the 2nd hidden layer has 2 output neurons
#X=[[1.,2.,3.,2.5],
 #  [2.0,5.0,-1,-0.8],
  # [0.7,1.7,2,9,-3.2]]
inputs=np.array([1,2,3,4])
class Layer_dense:
  def __init__(self, n_inputs,n_neurons):
    self.weights=0.10*np.random.randn(n_inputs,n_neurons)
    self.biases=np.zeros((1,n_neurons))
  def forward(self,inputs):
    self.output=np.dot(inputs,self.weights)+self.biases
  
class Activation_Relu:
  def forward(self,inputs):
    self.output=np.maximum(0,inputs)

class Activation_Softmax:
  def forward(self,inputs):
    exp_values=np.exp(inputs-np.max(inputs,axis=1,keepdims=True))
    probabilities=exp_values/np.sum(exp_values,axis=1,keepdims=True)
    self.output=probabilities

#you may design the number of hidden layer neurons what you want 
print("\nThe 1st hidder layer outputs\n")
layer1=Layer_dense(4,6)
#activation1=Activation_Relu()
activation1=Activation_Softmax()
layer1.forward(inputs)
#layer1.forward(X)
print(layer1.output)
activation1.forward(layer1.output)
print(activation1.output)
print(np.sum(activation1.output))
print("\nThe 2nd hidder layer outputs\n")

layer2=Layer_dense(6,10)
#activation2=Activation_Relu()
activation2=Activation_Softmax()
layer2.forward(activation1.output)
print(layer2.output)
activation2.forward(layer2.output)
print(activation2.output)
print(np.sum(activation2.output))




The 1st hidder layer outputs

[[ 0.71996132 -0.29539151 -0.81080693  0.66775876  1.00956271 -0.16528657]]
[[0.23384771 0.08471708 0.05059748 0.22195342 0.31239596 0.09648834]]
1.0

The 2nd hidder layer outputs

[[ 0.0563509  -0.04455413 -0.05269866  0.02532824 -0.02103229  0.0248367
  -0.01318179  0.00351179 -0.01576078 -0.12748163]]
[[0.10742829 0.0971172  0.09632944 0.10414674 0.09942865 0.10409556
  0.10021229 0.10189923 0.09995418 0.08938841]]
1.0


In [ ]:
##Hidden Layer Activation Functions

In [20]:
# Batches, Layers, and Objects
import numpy as np
np.random.seed(0)
#inputs [3,4], batchsize=3
#define hidden layer as an object
# The object has 3 features of weights, biases and output
# hidden layer size: the 1st hidden layer has 5 neurons and the 2nd hidden layer has 2 output neurons
X=[[1.,2.,3.,2.5],
   [2.0,5.0,-1,-0.8],
   [0.7,1.7,2,9,-3.2]]
#inputs=np.array([1,2,3,4])
class Layer_dense:
  def __init__(self, n_inputs,n_neurons):
    self.weights=0.10*np.random.randn(n_inputs,n_neurons)
    self.biases=np.zeros((1,n_neurons))
  def forward(self,inputs):
    self.output=np.dot(inputs,self.weights)+self.biases

#you may design the number of hidden layer neurons what you want 
layer1=Layer_dense(4,6)
layer2=Layer_dense(6,2)

#layer1.forward(inputs)
layer1.forward(X)
print(layer1.output)
layer2.forward(layer1.output)
print(layer2.output)


<string>:6: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.


ValueError: ignored